from pathlib import Path
root=Path('/mnt/data/ai_urdu_module1')

topics=[
{
'slug':'01-what-is-ai','title':'مصنوعی ذہانت کیا ہے؟','desc':'AI کا بنیادی مطلب، روزمرہ مثالیں، اور انسان کی مدد کرنے کا طریقہ۔','img':'ai-brain.svg',
'sections':[('AI کا آسان مطلب','مصنوعی ذہانت، جسے English میں Artificial Intelligence یا AI کہتے ہیں، ایسی ٹیکنالوجی ہے جو کمپیوٹر، موبائل ایپ یا مشین کو انسان جیسی کچھ ذہنی صلاحیتیں استعمال کرنے کے قابل بناتی ہے۔ مثال کے طور پر سمجھنا، جواب دینا، تصویر پہچاننا، آواز سننا، زبان ترجمہ کرنا، سفارش دینا، یا کسی کام کے لیے بہتر فیصلہ تجویز کرنا۔ AI انسان نہیں ہے، مگر یہ انسان کے بنائے ہوئے data، rules اور patterns کی مدد سے کام کرتا ہے۔'),('AI انسان کی طرح سوچتا ہے یا نہیں؟','عام AI حقیقت میں انسان کی طرح شعور، جذبات یا ذاتی تجربہ نہیں رکھتا۔ یہ patterns کو پہچانتا ہے اور پچھلے data کی بنیاد پر ممکنہ جواب بناتا ہے۔ جب آپ AI سے سوال کرتے ہیں تو وہ لفظوں، مثالوں، context اور ہدایات کی بنیاد پر ایک مناسب response تیار کرتا ہے۔ اس لیے AI بہت مددگار ہو سکتا ہے، لیکن اسے مکمل authority نہیں سمجھنا چاہیے۔'),('AI کیوں اہم ہے؟','AI اہم ہے کیونکہ یہ وقت بچاتا ہے، repetitive کام تیز کرتا ہے، بڑی معلومات کو آسان بناتا ہے، creative ideas دیتا ہے، customer support بہتر کرتا ہے، اور عام لوگوں کو بھی advanced tools تک رسائی دیتا ہے۔ پہلے بہت سے کام صرف experts کر سکتے تھے، مگر اب AI کی وجہ سے عام user بھی writing، planning، learning، design اور research میں بہتر output لے سکتا ہے۔'),('روزمرہ مثال','جب YouTube آپ کو next video suggest کرتا ہے، Google Maps traffic دیکھ کر route بتاتا ہے، phone آپ کی تصویر میں face identify کرتا ہے، یا chatbot فوراً جواب دیتا ہے، یہ سب AI یا AI-like systems کی مثالیں ہیں۔')],
'bullets':['AI ایک technology ہے جو data سے patterns سمجھتی ہے۔','AI انسان کی مدد کر سکتا ہے، انسان کی جگہ مکمل طور پر نہیں لیتا۔','AI کا result ہمیشہ verify کرنا چاہیے۔','AI کا استعمال writing، search، business، education اور daily life میں بڑھ رہا ہے۔'],
'quiz':[('AI کا بنیادی کام کیا ہے؟',['صرف انسان کی جگہ لینا','data اور patterns کی مدد سے کام کرنا','صرف games بنانا'],'data اور patterns کی مدد سے کام کرنا'),('کیا AI کے پاس انسانی شعور ہوتا ہے؟',['نہیں، عام AI میں شعور نہیں ہوتا','ہاں، ہمیشہ ہوتا ہے','صرف موبائل میں ہوتا ہے'],'نہیں، عام AI میں شعور نہیں ہوتا'),('AI کی ایک روزمرہ مثال کون سی ہے؟',['YouTube recommendations','کاغذی نوٹ بک','عام پنسل'],'YouTube recommendations')]
},
{
'slug':'02-ai-in-everyday-life','title':'AI روزمرہ زندگی میں کہاں استعمال ہوتا ہے؟','desc':'Search، shopping، maps، banking، entertainment اور mobile apps میں AI کا کردار۔','img':'tools.svg',
'sections':[('ہم AI کو پہلے ہی استعمال کر رہے ہیں','اکثر لوگ سمجھتے ہیں کہ AI کوئی future technology ہے، حالانکہ وہ روزانہ AI استعمال کر رہے ہوتے ہیں۔ Mobile keyboard کی suggestions، email spam filter، online shopping recommendations، maps کا traffic route، social media feed، banking fraud alerts، یہ سب AI کے عام استعمال ہیں۔'),('Search اور recommendations','Google Search، YouTube، Netflix، TikTok، Facebook اور Instagram آپ کے behavior، interests، clicks، watch time اور search history سے patterns سمجھتے ہیں۔ پھر system اندازہ لگاتا ہے کہ آپ کو کون سا content زیادہ relevant لگے گا۔ یہی وجہ ہے کہ ہر user کا feed مختلف ہوتا ہے۔'),('Mobile phone میں AI','Smartphone camera low light بہتر کرتا ہے، portrait mode میں background blur کرتا ہے، voice assistant بات سمجھتا ہے، keyboard اگلا word suggest کرتا ہے، اور photo gallery faces یا objects کے حساب سے images arrange کر سکتی ہے۔'),('Banking اور security','Banks suspicious transaction detect کرنے، fraud alerts بھیجنے، customer queries answer کرنے اور risk scoring کے لیے AI استعمال کر سکتے ہیں۔ AI بہت زیادہ transactions کو تیزی سے check کر لیتا ہے، جو انسان کے لیے manually مشکل ہوتا ہے۔')],
'bullets':['AI ہمیشہ robot کی شکل میں نہیں ہوتا، اکثر software کے اندر چھپا ہوتا ہے۔','Recommendations AI کا بہت عام استعمال ہیں۔','AI convenience بڑھاتا ہے مگر privacy awareness بھی ضروری ہے۔','Daily apps میں AI user behavior سے personalize experience بناتا ہے۔'],
'quiz':[('روزمرہ AI کی مثال کون سی ہے؟',['Spam filter','لکڑی کی میز','خالی کاغذ'],'Spam filter'),('Social media feed ہر user کے لیے مختلف کیوں ہوتا ہے؟',['AI user behavior سے اندازہ لگاتا ہے','Internet خود فیصلہ کرتا ہے','یہ random ہوتا ہے'],'AI user behavior سے اندازہ لگاتا ہے'),('Maps میں AI کس کام آ سکتا ہے؟',['Traffic route suggest کرنا','چائے بنانا','فون چارج کرنا'],'Traffic route suggest کرنا')]
},
{
'slug':'03-ai-automation-software','title':'AI، Automation اور عام Software میں فرق','desc':'تینوں concepts کو آسان مثالوں کے ساتھ سمجھیں تاکہ confusion ختم ہو۔','img':'data-flow.svg',
'sections':[('عام Software کیا ہے؟','عام software پہلے سے لکھی ہوئی instructions پر چلتا ہے۔ مثال کے طور پر calculator میں 2 + 2 لکھیں تو جواب 4 آئے گا۔ اگر rule موجود ہے تو software کام کرے گا، اگر rule نہیں ہے تو عموماً خود سے نیا solution نہیں نکالے گا۔'),('Automation کیا ہے؟','Automation کسی repeat ہونے والے کام کو خودکار بنانا ہے۔ مثال: ہر Monday صبح ایک email automatically send ہو جائے، form submit ہونے پر customer کو SMS چلا جائے، یا invoice بن کر save ہو جائے۔ Automation بہت useful ہے، لیکن یہ زیادہ تر fixed rules پر چلتی ہے۔'),('AI کیا مختلف کرتا ہے؟','AI fixed rules کے ساتھ ساتھ patterns، examples اور context کی بنیاد پر flexible output دے سکتا ہے۔ مثال کے طور پر customer کے مختلف سوالات پڑھ کر AI مختلف انداز میں جواب بنا سکتا ہے، image دیکھ کر object پہچان سکتا ہے، یا long document کا summary بنا سکتا ہے۔'),('فرق کو ایک مثال سے سمجھیں','عام software: invoice number generate کرے گا۔ Automation: invoice بننے کے بعد email send کرے گی۔ AI: invoice data دیکھ کر بتا سکتا ہے کہ کون سے clients late payment کے risk میں ہیں یا email کا polite follow-up draft کر سکتا ہے۔')],
'bullets':['Software rule-based ہو سکتا ہے۔','Automation repetitive workflow کو خودکار بناتی ہے۔','AI context اور patterns سے flexible output بناتا ہے۔','بہترین systems میں تینوں چیزیں ساتھ استعمال ہوتی ہیں۔'],
'quiz':[('Automation کی بہترین مثال کیا ہے؟',['ہر form submit ہونے پر auto email جانا','انسان کا خود email لکھنا','کاغذ پر نام لکھنا'],'ہر form submit ہونے پر auto email جانا'),('AI عام software سے کیسے مختلف ہو سکتا ہے؟',['یہ context کے مطابق جواب بنا سکتا ہے','یہ کبھی data استعمال نہیں کرتا','یہ صرف calculator ہے'],'یہ context کے مطابق جواب بنا سکتا ہے'),('Invoice example میں AI کیا کر سکتا ہے؟',['Risk یا follow-up draft suggest کرنا','صرف کاغذ پکڑنا','printer صاف کرنا'],'Risk یا follow-up draft suggest کرنا')]
},
{
'slug':'04-types-of-ai','title':'AI کی اہم اقسام','desc':'Narrow AI، Generative AI، Predictive AI، Conversational AI اور General AI کا سادہ تعارف۔','img':'ai-brain.svg',
'sections':[('Narrow AI','Narrow AI وہ AI ہے جو ایک مخصوص کام یا محدود کاموں کے لیے بنایا جاتا ہے۔ آج دنیا میں زیادہ تر AI اسی category میں آتا ہے۔ مثال: face recognition، spam filter، chatbot، recommendation system، translation tool۔ یہ اپنے کام میں طاقتور ہو سکتا ہے مگر ہر چیز نہیں کر سکتا۔'),('Generative AI','Generative AI نیا content بناتا ہے۔ یہ text، image، video، music، code، presentation، ideas یا designs create کر سکتا ہے۔ ChatGPT جیسے tools text generate کرتے ہیں، image tools pictures بناتے ہیں، video tools clips بنانے میں مدد دیتے ہیں۔'),('Predictive AI','Predictive AI پچھلے data کی بنیاد پر مستقبل کا اندازہ لگاتا ہے۔ مثال: کون سا customer خریداری کر سکتا ہے، کون سا transaction fraud ہو سکتا ہے، sales اگلے month بڑھیں گی یا کم ہوں گی، یا weather کا trend کیا ہو سکتا ہے۔'),('Conversational AI','Conversational AI انسانوں سے بات چیت کرتا ہے۔ Chatbots، virtual assistants، customer support bots اور voice assistants اس کی مثالیں ہیں۔ اچھا conversational AI context سمجھتا ہے، follow-up questions handle کرتا ہے اور user کو آسان جواب دیتا ہے۔'),('General AI','General AI ایسی AI کو کہا جاتا ہے جو انسان جیسی broad intelligence رکھے اور مختلف fields میں خود سے سمجھ کر کام کر سکے۔ یہ ابھی practical عام زندگی میں موجود نہیں ہے۔ آج زیادہ تر tools specialized یا narrow AI ہیں۔')],
'bullets':['آج کا زیادہ تر AI narrow AI ہے۔','Generative AI نیا content بناتا ہے۔','Predictive AI اندازہ یا forecast لگاتا ہے۔','General AI ابھی زیادہ تر concept/future discussion ہے۔'],
'quiz':[('Generative AI کیا کرتا ہے؟',['نیا content بناتا ہے','صرف بجلی چلاتا ہے','صرف physical robot بناتا ہے'],'نیا content بناتا ہے'),('Predictive AI کس لیے استعمال ہو سکتا ہے؟',['Future trend کا اندازہ','کمرہ paint کرنا','mobile cover بنانا'],'Future trend کا اندازہ'),('آج زیادہ تر AI کس قسم کا ہے؟',['Narrow AI','General AI','Magic AI'],'Narrow AI')]
},
{
'slug':'05-how-ai-learns','title':'AI کیسے سیکھتا ہے؟','desc':'Data، training، patterns، feedback اور improvement کو آسان زبان میں سمجھیں۔','img':'data-flow.svg',
'sections':[('AI کو examples کی ضرورت ہوتی ہے','AI عموماً examples سے سیکھتا ہے۔ اگر system کو ہزاروں تصاویر دکھائی جائیں جن میں بلی اور کتا label کیے گئے ہوں، تو وہ shapes، colors، ears، eyes اور دیگر patterns سے فرق سمجھنا شروع کرتا ہے۔ یہ انسانی بچے کے سیکھنے جیسا لگ سکتا ہے، لیکن AI تجربہ نہیں رکھتا، صرف mathematical patterns بناتا ہے۔'),('Training کیا ہوتی ہے؟','Training وہ process ہے جس میں AI model کو بہت سا data دیا جاتا ہے تاکہ وہ patterns identify کرے۔ یہ data text، images، audio، numbers یا videos ہو سکتا ہے۔ Training کے بعد model نئے input پر response یا prediction دیتا ہے۔'),('Feedback سے بہتری','اگر AI غلطی کرے اور اسے correct feedback ملے تو system کو بہتر بنایا جا سکتا ہے۔ بعض tools user feedback، ratings یا human review سے improve ہوتے ہیں۔ مگر ہر AI tool real-time میں user سے فوراً نہیں سیکھتا؛ کچھ models کو بعد میں update کیا جاتا ہے۔'),('Good data کیوں ضروری ہے؟','اگر data کمزور، biased، outdated یا غلط ہو تو AI کا result بھی کمزور ہو سکتا ہے۔ اسی لیے data quality AI quality کا اہم حصہ ہے۔ AI کو اچھے examples، clear labels، balanced information اور testing کی ضرورت ہوتی ہے۔')],
'bullets':['AI examples سے patterns سیکھتا ہے۔','Training میں model کو data دیا جاتا ہے۔','Feedback improvement میں مدد دیتا ہے۔','Poor data سے poor results آ سکتے ہیں۔'],
'quiz':[('AI training میں کیا استعمال ہوتا ہے؟',['Data اور examples','صرف پانی','صرف keyboard'],'Data اور examples'),('اگر data غلط ہو تو کیا ہو سکتا ہے؟',['AI کا result بھی غلط ہو سکتا ہے','AI ہمیشہ درست رہے گا','data کا کوئی اثر نہیں'],'AI کا result بھی غلط ہو سکتا ہے'),('Feedback کا فائدہ کیا ہے؟',['AI system کو بہتر بنانے میں مدد','screen روشن کرنا','mouse تیز کرنا'],'AI system کو بہتر بنانے میں مدد')]
},
{
'slug':'06-machine-learning','title':'Machine Learning کیا ہے؟','desc':'Machine Learning کو examples، patterns اور prediction کے ذریعے سمجھیں۔','img':'data-flow.svg',
'sections':[('Machine Learning کی تعریف','Machine Learning یا ML، AI کا ایک اہم حصہ ہے۔ اس میں computer کو ہر rule manually بتانے کے بجائے examples دیے جاتے ہیں تاکہ وہ data سے pattern سیکھے اور نئے cases پر prediction یا decision دے سکے۔'),('ایک آسان مثال','فرض کریں آپ کے پاس گھروں کی prices کا data ہے: area، rooms، location، condition، اور final price۔ ML model اس data سے pattern سیکھتا ہے اور پھر کسی نئے گھر کی estimated price بتا سکتا ہے۔ یہ guarantee نہیں، prediction ہے۔'),('Supervised اور Unsupervised کا آسان تصور','Supervised learning میں examples کے ساتھ correct answers بھی ہوتے ہیں، جیسے email spam ہے یا نہیں۔ Unsupervised learning میں AI data کے اندر groups یا hidden patterns تلاش کرتا ہے، جیسے customers کو behavior کے حساب سے segments میں تقسیم کرنا۔'),('Machine Learning کہاں استعمال ہوتی ہے؟','ML fraud detection، recommendations، image recognition، speech recognition، customer segmentation، medical support، sales forecasting، hiring tools اور logistics planning میں استعمال ہو سکتی ہے۔')],
'bullets':['Machine Learning AI کا حصہ ہے۔','ML examples سے patterns سیکھتی ہے۔','ML prediction دیتی ہے، ہمیشہ guarantee نہیں۔','Supervised learning میں labeled examples ہوتے ہیں۔'],
'quiz':[('Machine Learning میں computer کیسے سیکھتا ہے؟',['Examples اور data سے','صرف manual rules سے','paper reading سے'],'Examples اور data سے'),('House price estimation کس چیز کی مثال ہے؟',['Prediction','Cooking','Printing'],'Prediction'),('Supervised learning میں کیا ہوتا ہے؟',['Examples کے ساتھ correct answers ہوتے ہیں','کوئی data نہیں ہوتا','صرف images ہوتی ہیں'],'Examples کے ساتھ correct answers ہوتے ہیں')]
},
{
'slug':'07-generative-ai','title':'Generative AI کیا ہے؟','desc':'Text، images، videos، music، code اور creative content بنانے والی AI کو سمجھیں۔','img':'tools.svg',
'sections':[('Generative AI کا مطلب','Generative AI وہ AI ہے جو نیا content generate کرتی ہے۔ یہ user کے prompt کی بنیاد پر paragraphs، captions، emails، reports، images، videos، scripts، music ideas، code اور presentations بنا سکتی ہے۔'),('Prompt کیوں اہم ہے؟','Generative AI کا output prompt پر بہت depend کرتا ہے۔ اگر آپ vague instruction دیں گے تو answer بھی vague ہو سکتا ہے۔ اگر آپ task، audience، tone، format، length اور example دیں گے تو result بہتر ہو گا۔'),('Generative AI کیا کر سکتی ہے؟','یہ brainstorming، writing، editing، translation، summarization، design concepts، ad copy، lesson plans، quiz questions، customer replies، social media calendars، video scripts اور basic code میں مدد کر سکتی ہے۔'),('حدود اور احتیاط','Generative AI غلط facts دے سکتی ہے، outdated information استعمال کر سکتی ہے، یا ایسا content بنا سکتی ہے جو legally یا ethically review مانگتا ہو۔ اس لیے important work میں human review، fact-checking اور source verification ضروری ہے۔')],
'bullets':['Generative AI نیا content create کرتی ہے۔','Prompt جتنا clear ہو، output اتنا بہتر ہوتا ہے۔','یہ creative assistant ہے، final authority نہیں۔','Fact-checking ضروری ہے، خاص طور پر sensitive topics میں۔'],
'quiz':[('Generative AI کیا بنا سکتی ہے؟',['Text اور images جیسے content','صرف physical chairs','صرف electricity'],'Text اور images جیسے content'),('اچھے output کے لیے کیا ضروری ہے؟',['Clear prompt','خاموش رہنا','random click کرنا'],'Clear prompt'),('Generative AI کے output کو کب review کرنا چاہیے؟',['Important یا factual کام میں','کبھی نہیں','صرف game میں'],'Important یا factual کام میں')]
},
{
'slug':'08-popular-ai-tools','title':'مشہور AI Tools اور ان کا استعمال','desc':'Writing، research، design، video، productivity اور business tools کی categories۔','img':'tools.svg',
'sections':[('Tools کو category کے حساب سے سمجھیں','AI tools کو names سے زیادہ categories کے حساب سے سمجھنا بہتر ہے، کیونکہ tools بدلتے رہتے ہیں۔ عام categories میں writing assistants، research tools، image generators، video tools، coding assistants، meeting note tools، automation tools اور business chatbots شامل ہیں۔'),('Writing اور communication tools','یہ tools emails، captions، reports، summaries، proposals، translations، FAQs، customer replies اور learning material بنانے میں مدد دیتے ہیں۔ عام public کے لیے یہ سب سے accessible AI category ہے۔'),('Design، image اور video tools','Image AI tools posters، concepts، product visuals، backgrounds اور creative references بنا سکتے ہیں۔ Video AI tools scripts، subtitles، voiceovers، clips، scene ideas اور editing support دے سکتے ہیں۔ Final quality کے لیے human designer یا editor کی نظر اب بھی اہم ہے۔'),('Research اور productivity tools','AI research tools long documents summarize کر سکتے ہیں، key points نکال سکتے ہیں، comparison tables بنا سکتے ہیں، meeting notes organize کر سکتے ہیں، tasks plan کر سکتے ہیں اور checklists generate کر سکتے ہیں۔'),('Tool choose کرنے کا طریقہ','Tool select کرتے وقت یہ دیکھیں: آپ کا goal کیا ہے، privacy policy کیا ہے، free/paid limits کیا ہیں، output quality کیسی ہے، Urdu/English support کیسی ہے، اور کیا tool آپ کے workflow میں fit بیٹھتا ہے۔')],
'bullets':['Tools بدلتے رہتے ہیں، categories سمجھنا زیادہ useful ہے۔','Writing tools beginners کے لیے بہترین start ہیں۔','Design/video tools creative support دیتے ہیں۔','Privacy اور cost check کرنا ضروری ہے۔'],
'quiz':[('AI tools کو بہتر سمجھنے کا طریقہ کیا ہے؟',['Category کے حساب سے','صرف logo کے رنگ سے','صرف قیمت سے'],'Category کے حساب سے'),('Writing AI tools کس میں مدد دے سکتے ہیں؟',['Emails اور summaries','گاڑی wash کرنا','کمرہ تعمیر کرنا'],'Emails اور summaries'),('Tool choose کرتے وقت کیا check کرنا چاہیے؟',['Goal، privacy، cost، quality','صرف نام','صرف font'],'Goal، privacy، cost، quality')]
}
]

index='''<!doctype html><html lang="ur" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>AI Learning Urdu | Module 1</title><link rel="stylesheet" href="assets/style.css"></head><body><header class="site-header"><div class="container"><nav class="nav"><a class="brand" href="index.html">AI Learning Guide</a><a href="#topics">Module 1 Topics</a></nav><section class="hero"><div><span class="badge">Module 1</span><h1>مصنوعی ذہانت کا تعارف</h1><p>یہ guide عام public کے لیے بنائی گئی ہے تاکہ AI کو آسان، practical اور readable انداز میں سمجھا جا سکے۔ ہر topic میں examples، key points اور quick quiz شامل ہیں۔</p><a class="btn secondary" href="#topics">Topics شروع کریں</a></div><div class="hero-card"><img src="assets/ai-brain.svg" alt="AI Brain" style="width:100%;height:auto"><p class="small">Basic level سے شروع کریں، پھر practical اور advanced topics تک آسانی سے بڑھیں۔</p></div></section></div></header><main class="main"><div class="container"><section class="grid"><div class="card"><h3>کس کے لیے؟</h3><p>Students، business owners، marketers، teachers، employees اور وہ تمام لوگ جو AI کو technical jargon کے بغیر سمجھنا چاہتے ہیں۔</p></div><div class="card"><h3>Learning Style</h3><p>ہر topic میں سادہ explanation، روزمرہ مثالیں، useful warnings، اور short quiz ہے تاکہ concept check ہو سکے۔</p></div><div class="card"><h3>Language</h3><p>Content Urdu میں ہے، مگر مشکل technical terms کے لیے مناسب English words بھی استعمال کیے گئے ہیں۔</p></div></section><section id="topics" style="margin-top:34px"><h2>Module 1: Introduction to AI</h2><p>نیچے دیے گئے 8 topics AI کی بنیاد مضبوط کرنے کے لیے ترتیب دیے گئے ہیں۔</p><div class="module-list">'''
for i,t in enumerate(topics,1):
    index += f'''<a class="topic-link" href="topics/{t['slug']}.html"><span class="topic-number">{i:02d}</span><span><strong>{t['title']}</strong><p>{t['desc']}</p></span><span class="arrow">←</span></a>'''
index += '''</div></section></div></main><footer class="footer"><div class="container">© AI Learning Guide | Module 1 Urdu</div></footer><script src="assets/app.js"></script></body></html>'''
(root/'index.html').write_text(index,encoding='utf-8')

for idx,t in enumerate(topics,1):
    prev=topics[idx-2]['slug']+'.html' if idx>1 else None
    nxt=topics[idx]['slug']+'.html' if idx<len(topics) else None
    page=f'''<!doctype html><html lang="ur" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>{t['title']} | AI Learning Urdu</title><link rel="stylesheet" href="../assets/style.css"></head><body><div class="topbar"><div class="container"><div><a href="../index.html">← واپس Index پر</a> <span class="small">/ Topic {idx:02d}</span></div><div class="progress" style="width:220px"><span></span></div></div></div><main class="main"><div class="container content-layout"><aside class="toc"><strong>اس page میں</strong><ul><li><a href="#intro">تعارف</a></li><li><a href="#details">تفصیل</a></li><li><a href="#keypoints">اہم نکات</a></li><li><a href="#quiz">Quick Quiz</a></li></ul></aside><article class="article"><span class="badge">Module 1 • Topic {idx:02d}</span><h1 id="intro">{t['title']}</h1><p>{t['desc']}</p><div class="visual"><img src="../assets/{t['img']}" alt="{t['title']}"></div><section id="details">'''
    for h,p in t['sections']:
        cls='example' if 'مثال' in h else ''
        page += f'<h2>{h}</h2><p>{p}</p>'
    page += f'''</section><section id="keypoints"><h2>اہم نکات</h2><ul>'''
    for b in t['bullets']:
        page += f'<li>{b}</li>'
    page += '''</ul><div class="note"><strong>یاد رکھیں:</strong> AI کو ایک مددگار assistant سمجھیں۔ بہتر results کے لیے clear instructions دیں اور اہم معلومات کو خود verify کریں۔</div></section>'''
    # add comparison table on some pages
    if idx==3:
        page += '''<h2>مختصر comparison</h2><div class="table-wrap"><table><tr><th>Concept</th><th>آسان مطلب</th><th>مثال</th></tr><tr><td>Software</td><td>پہلے سے لکھی ہوئی instructions</td><td>Calculator</td></tr><tr><td>Automation</td><td>repeat کام کو خودکار بنانا</td><td>Auto email</td></tr><tr><td>AI</td><td>patterns اور context سے flexible output</td><td>Chatbot reply یا summary</td></tr></table></div>'''
    if idx==4:
        page += '''<h2>AI Types کا quick view</h2><div class="table-wrap"><table><tr><th>Type</th><th>کام</th><th>Example</th></tr><tr><td>Narrow AI</td><td>مخصوص کام</td><td>Spam filter</td></tr><tr><td>Generative AI</td><td>نیا content</td><td>Text/image generator</td></tr><tr><td>Predictive AI</td><td>اندازہ</td><td>Sales forecast</td></tr><tr><td>Conversational AI</td><td>بات چیت</td><td>Chatbot</td></tr></table></div>'''
    page += f'''<section id="quiz" class="quiz"><h2>Quick Quiz</h2><p>جواب select کریں اور check button دبائیں۔</p><form id="quizForm">'''
    answers={}
    for q_i,(q,opts,ans) in enumerate(t['quiz'],1):
        name=f'q{q_i}'; answers[name]=ans
        page += f'<div class="q"><p>{q_i}. {q}</p>'
        for opt in opts:
            page += f'<label><input type="radio" name="{name}" value="{opt}"> {opt}</label>'
        page += '</div>'
    import json
    page += f'''<button type="button" class="btn" onclick='checkQuiz("quizForm", {json.dumps(answers,ensure_ascii=False)})'>Quiz Check کریں</button><div class="result"></div></form></section><div class="page-actions">'''
    if prev: page += f'<a class="btn" href="{prev}">پچھلا Topic</a>'
    page += '<a class="btn secondary" href="../index.html">Index</a>'
    if nxt: page += f'<a class="btn" href="{nxt}">اگلا Topic</a>'
    page += '''</div></article></div></main><footer class="footer"><div class="container">AI Learning Guide | Urdu Module 1</div></footer><script src="../assets/app.js"></script></body></html>'''
    (root/'topics'/f"{t['slug']}.html").write_text(page,encoding='utf-8')
print('done')
